spring:
  application:
    name: keycloak-admin
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: howerdown1995
    url: jdbc:postgresql://localhost:5432/keycloak
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
