spring:
  application:
    name: keycloak-admin
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/keycloak
  jpa:
    hibernate:
      ddl-auto: validate