spring:
  application:
    name: keycloak-admin
  datasource:
    driverClassName: org.postgresql.Driver
    username: @db-username@
    password: @db-password@
    url: @db-url@
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
    url: @db-url@
    user: @db-username@
    password: @db-password@